NUnit/assignment3/Models/ErrorViewModel.cs
namespace assignment3.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

NUnit/assignment3/Models/PersonCreateModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace assignment3.Models
{
    public class PersonCreateModel
    {
        [DisplayName("First Name")]
        [Required(ErrorMessage = "{0} is required")]
        [MaxLength(10)]
        public string? FirstName { get; set; }

        public string? LastName { get; set; }

        public string? Gender { get; set; }

        public DateTime DateOfBirth { get; set; }

        public string? PhoneNumber { get; set; }

        public string? BirthPlace { get; set; }
    }
}

NUnit/assignment3/Models/PersonDetailModel.cs
namespace assignment3.Models
{
    public class PersonDetailModel
    {
        public string? FirstName { get; set; }

        public string? LastName { get; set; }

        public string? Gender { get; set; }

        public DateTime DateOfBirth { get; set; }

        public string? PhoneNumber { get; set; }

        public string? BirthPlace { get; set; }
    }
}

NUnit/assignment3/Models/PersonEditModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace assignment3.Models
{
    public class PersonEditModel
    {
        [Required, DisplayName("First Name")]
        public string? FirstName { get; set; }

        [Required, DisplayName("Last Name")]
        public string? LastName { get; set; }

        public string? PhoneNumber { get; set; }

        public string? BirthPlace { get; set; }

        //public int Index {get; set;}
    }
}

NUnit/assignment3/Models/PersonModel.cs
namespace assignment3.Models
{
    public class PersonModel
    {
        public string? FirstName { get; set; }

        public string? LastName { get; set; }

        public string? Gender { get; set; }

        public DateTime DateOfBirth { get; set; }

        public string? PhoneNumber { get; set; }

        public string? BirthPlace { get; set; }

        public uint Age
        {
            get
            {
                return (uint)(DateTime.Now.Year - DateOfBirth.Year);
            }
        }

        public bool IsGraduated { get; set; }

        public string? GraduatedString
        {
            get
            {
                if (IsGraduated == true)
                {
                    return "Is Graduated";
                }
                else
                {
                    return "Is Not Graduated";
                }
            }
        }

        private string? _fullName;

        public string FullName
        {
            get
            {
                _fullName = FirstName + " " + LastName;
                return _fullName;
            }
        }
    }
}

NUnit/assignment3/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using assignment3.Models;

namespace assignment3.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

NUnit/assignment3/Controllers/RookiesController.cs
using Microsoft.AspNetCore.Mvc;
using assignment3.Models;
using assignment3.Services;

namespace assignment3.Controllers
{
    public class RookiesController : Controller
    {
        private readonly ILogger<RookiesController> _logger;
        private readonly IPersonService _personService;

        public RookiesController(ILogger<RookiesController> logger, IPersonService personService)
        {
            _logger = logger;
            _personService = personService;
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }

        public IActionResult Index()
        {
            var models = _personService.GetAll();
            return View(models);
        }

        public IActionResult Details(int index)
        {
            var person = _personService.GetOne(index);
            if (person != null)
            {
                var model = new PersonModel
                {
                    FirstName = person.FirstName,
                    LastName = person.LastName,
                    Gender = person.Gender,
                    DateOfBirth = person.DateOfBirth,
                    PhoneNumber = person.PhoneNumber,
                    BirthPlace = person.BirthPlace,
                };
                ViewData["Index"] = index;
                return View(model);
            }
            return View();
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(PersonModel model)
        {
            if (ModelState.IsValid)
            {
                var person = new PersonModel
                {
                    FirstName = model.FirstName,
                    LastName = model.LastName,
                    Gender = model.Gender,
                    DateOfBirth = model.DateOfBirth,
                    PhoneNumber = model.PhoneNumber,
                    BirthPlace = model.BirthPlace,
                    IsGraduated = false
                };
                _personService.Create(person);

                return RedirectToAction("Index");
            }

            return View(model);
        }

        [HttpGet]
        public IActionResult Edit(int index)
        {
            var person = _personService.GetOne(index);
            if (person != null)
            {
                var model = new PersonEditModel
                {
                    FirstName = person.FirstName,
                    LastName = person.LastName,
                    PhoneNumber = person.PhoneNumber,
                    BirthPlace = person.BirthPlace,
                };
                ViewData["Index"] = index;
                return View(model);
            }
            return View();
        }

        [HttpPost]
        public IActionResult Update(int index, PersonEditModel model)
        {
            if (ModelState.IsValid)
            {
                var person = _personService.GetOne(index);
                if (person != null)
                {
                    person.FirstName = model.FirstName;
                    person.LastName = model.LastName;
                    person.PhoneNumber = model.PhoneNumber;
                    person.BirthPlace = model.BirthPlace;

                    _personService.Update(index, person);
                }

                return RedirectToAction("Index");
            }

            return View(model);
        }

        [HttpPost]
        public IActionResult Delete(int index)
        {
            var result = _personService.Delete(index);
            if (result == null)
            {
                return NotFound();
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult DeleteAndRedirected(int index)
        {
            var result = _personService.Delete(index);
            if (result == null) return NotFound();

            HttpContext.Session.SetString("DeletedPersonName", result.FullName);

            return RedirectToAction("DeleteResult");
        }

        public IActionResult DeleteResult()
        {
            return View();
        }
    }
}

NUnit/assignment3/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

NUnit/assignment3/Views/Rookies/Create.cshtml
@model PersonCreateModel

@{
  ViewData["Title"] = "Create new person";
}

<div class="">
  <h1 class="display-4 text-center">Create new person</h1>
  <div class="row">
    <form asp-controller="Rookies" asp-action="Create" method="post" class="col-4 offset-4">
      <div class="form-group">
        <label asp-for="FirstName"></label>
        <input asp-for="FirstName" type="text" class="form-control" id="exampleInputEmail1"
          placeholder="Your first name">
        <span asp-validation-for="FirstName" class="form-text text-danger"></span>
      </div>
      <div class="form-group">
        <label asp-for="LastName"></label>
        <input asp-for="LastName" type="text" class="form-control" id="exampleInputEmail1" placeholder="Your last name">
        <span asp-validation-for="LastName" class="form-text text-danger"></span>
      </div>
      <div class="form-group">
        <label asp-for="Gender"></label>
        <select class="form-control" asp-for="Gender" aria-label=".form-select-sm example">
          <option value="Male" selected>Male</option>
          <option value="Female">Female</option>
          <option value="Other">Other</option>
        </select>
      </div>
      <div class="form-group">
        <label asp-for="DateOfBirth"></label>
        <input asp-for="DateOfBirth" type="date" class="form-control" id="exampleInputEmail1"
          placeholder="Your date of birth">
        <span asp-validation-for="DateOfBirth" class="form-text text-danger"></span>
      </div>
      <div class="form-group">
        <label asp-for="PhoneNumber"></label>
        <input asp-for="PhoneNumber" type="text" class="form-control" id="exampleInputEmail1"
          placeholder="Your phone number">
        <span asp-validation-for="PhoneNumber" class="form-text text-danger"></span>
      </div>
      <div class="form-group">
        <label asp-for="BirthPlace"></label>
        <input asp-for="BirthPlace" type="text" class="form-control" id="exampleInputEmail1"
          placeholder="Your birth place">
        <span asp-validation-for="BirthPlace" class="form-text text-danger"></span>
      </div>
      <button class="btn btn-success btn-sm" type="submit">Submit</button>
    </form>
  </div>
</div>

NUnit/assignment3/Views/Rookies/DeleteResult.cshtml
@inject IHttpContextAccessor HttpContextAccessor

@{
    ViewData["Title"] = "Delete result";
    var deletedPerson = HttpContextAccessor?.HttpContext?.Session.GetString("DeletedPersonName") ?? "[unknown person]";
}
<h1 class="display-6 text-center text-info">Person @deletedPerson is removed susscessfully</h1>

NUnit/assignment3/Views/Rookies/Details.cshtml
@model PersonDetailModel

@{
    ViewData["Title"] = "Person Information";
    var value = ViewData["Index"]?.ToString() ?? "";
    var index = !string.IsNullOrEmpty(value) ? int.Parse(value) : 0;
}

<div class="">
    <h1 class="display-4 text-center">Person Information</h1>
    <div class="row">
        <form asp-controller="Rookies" asp-action="Details" asp-route-index="@index" method="post"
            class="col-4 offset-4">
            <div class="form-group">
                <label asp-for="FirstName"></label>
                <label asp-for="FirstName" type="text" class="form-control">@Model.FirstName</label>
            </div>
            <div class="form-group">
                <label asp-for="LastName"></label>
                <label asp-for="LastName" type="text" class="form-control">@Model.LastName</label>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber"></label>
                <label asp-for="PhoneNumber" type="text" class="form-control">@Model.PhoneNumber</label>
            </div>
            <div class="form-group">
                <label asp-for="BirthPlace"></label>
                <label asp-for="BirthPlace" type="text" class="form-control">@Model.BirthPlace</label>
            </div>
            <div class="form-group mt-4">
                <a class="btn btn-success btn-sm" role="button" asp-controller="Rookies" asp-action="Index">Back To
                    Title</a>
                <a role="button" class="btn btn-danger btn-sm" href="#" data-bs-toggle="modal"
                    data-bs-target="#exampleModal">Delete</a>
            </div>
        </form>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <form asp-controller="Rookies" asp-action="DeleteAndRedirected" asp-route-index="@index" method="post"
                class="col-8 offset-2">
                <div class="modal-header">
                    <h1 class="modal-title fs-6 text-dark" id="exampleModalLabel">Delete
                        Confirmation</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body" class="text-dark">
                    <h2 class="text-dark fs-6"> Are you sure you want to delete ? </h2>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Confirm</button>
                </div>
            </form>
        </div>
    </div>
</div>

NUnit/assignment3/Views/Rookies/Edit.cshtml
@model PersonEditModel

@{
    ViewData["Title"] = "Update person info";
    var value = ViewData["Index"]?.ToString() ?? "";
    var index = !string.IsNullOrEmpty(value) ? int.Parse(value) : 0;
}

<div class="">
    <h1 class="display-4 text-center">Update person info</h1>
    <div class="row">
        <form asp-controller="Rookies" asp-action="Update" asp-route-index="@index" method="post"
            class="col-4 offset-4">
            <div class="form-group">
                <label asp-for="FirstName"></label>
                <input asp-for="FirstName" type="text" class="form-control" id="exampleInputEmail1"
                    placeholder="Your first name">
                <span asp-validation-for="FirstName" class="form-text text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName"></label>
                <input asp-for="LastName" type="text" class="form-control" id="exampleInputEmail1"
                    placeholder="Your last name">
                <span asp-validation-for="LastName" class="form-text text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber"></label>
                <input asp-for="PhoneNumber" type="text" class="form-control" id="exampleInputEmail1"
                    placeholder="Your phone number">
                <span asp-validation-for="PhoneNumber" class="form-text text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BirthPlace"></label>
                <input asp-for="BirthPlace" type="text" class="form-control" id="exampleInputEmail1"
                    placeholder="Your birth place">
                <span asp-validation-for="BirthPlace" class="form-text text-danger"></span>
            </div>
            <div class="form-group mt-4">
                <button class="btn btn-success btn-sm" type="submit">Submit</button>
                <a class="btn btn-danger btn-sm" role="button" asp-controller="Rookies" asp-action="Index">Cancel</a>
            </div>
        </form>
    </div>
</div>

NUnit/assignment3/Views/Rookies/Index.cshtml
@model IList<assignment3.Models.PersonModel>

@{
    ViewData["Title"] = "Rookie Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome ! This is the Rookie List</h1>
    <div class="text-start mt=2 mb=4">
        <a class="btn btn-success btn-sm" role="button" asp-action="Create">Create New Person</a>
    </div>
    <table class="table table-dark table-striped">
        <thead class="thead-dark">
            <tr>
                <th scope="col">#</th>
                <th scope="col">Full Name</th>
                <th scope="col">Date Of Birth</th>
                <th scope="col">Gender</th>
                <th scope="col">Birth Place</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
            @for (int i = 0; i < Model.Count(); i++)
            {
                var person = Model[i];
                <tr>
                    <th scope="row">@(i + 1)</th>
                    <td class="text-left">
                        <a asp-controller="Rookies" asp-action="Details" asp-route-index="@i">@person.FullName</a>
                    </td>
                    <td>@person.DateOfBirth.ToString("dd/MM/yyyy")</td>
                    <td>@person.Gender</td>
                    <td>@person.BirthPlace</td>
                    <td>
                        <a role="button" class="btn btn-primary btn-sm" asp-controller="Rookies" asp-action="Edit"
                        asp-route-index="@i">Edit</a>
                        <a role="button" class="btn btn-danger btn-sm" href="#" data-bs-toggle="modal"
                        data-bs-target="#exampleModal_@i">Delete</a>

                        <!-- Modal -->
                    <div class="modal fade" id="exampleModal_@i" tabindex="-1" aria-labelledby="exampleModalLabel"
                        aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <form asp-controller="Rookies" asp-action="Delete" asp-route-index="@i" method="post"
                                    class="col-8 offset-2">
                                        <div class="modal-header">
                                            <h1 class="modal-title fs-6 text-dark" id="exampleModalLabel">Delete
                                                Confirmation</h1>
                                            <button type="button" class="btn-close" data-bs-dismiss="modal"
                                            aria-label="Close"></button>
                                        </div>
                                        <div class="modal-body" class="text-dark">
                                            <h2 class="text-dark fs-6"> Are you sure you want to delete ? </h2>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary"
                                            data-bs-dismiss="modal">Close</button>
                                            <button type="submit" class="btn btn-primary">Confirm</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

NUnit/assignment3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - assignment3</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/assignment3.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">assignment3</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Rookies"
                                asp-action="Index">Rookies</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - assignment3 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>